commit_message: 🔄 Update file via sync

replace:
  - before: project_name
    after: Stats For GitHub
  - before: project_description
    after: 🐙 iOS and iPadOS widgets for your GitHub stats
  - before: project_author_email
    after: magnesiumsoftware@gmail.com

files:
  - path: LICENSE.md
    source: https://github.com/Magnesium-Software/shared/blob/main/licenses/gnu-gpl-v3.md
  - path: CODE_OF_CONDUCT.md
    source: https://github.com/Magnesium-Software/shared/blob/main/docs/coc.md
  - path: .github/workflows/sync.yml
    source: https://github.com/Magnesium-Software/shared/blob/main/workflows/sync.yml
  - path: .github/workflows/lint.yml
    source: https://github.com/Magnesium-Software/shared/blob/main/workflows/lint.yml
  - path: .gitignore
    source: https://github.com/Magnesium-Software/shared/blob/main/config/.gitignore
